
export const STRINGS = {
    'file.new.name': 'New File',
    'file.open.name': 'Open File',
    'file.save-as.name': 'Save to...',
    'file.save-active.name': 'Save to Current File',
    'file.export-as.name': 'Export to...',
    'file.export-active.name': 'Export to Current File',
    'file.save-warning': 'Opening a new file will replace your existing content.\n' +
        'Click \'Save\' if you want to back up your drawing first.',
    'file.save-warning-cleared': 'Your current file has been saved. You may proceed to opening a new file.',
    'file.cannot-rename-active-file.name': 'Cannot rename disk file',
    'file.cannot-rename-active-file.description': 'This file exists on your computer and cannot be renamed from the browser. ' +
        'To rename it, save a copy with a new name and manually delete the original file.',
    'file.active-file-info.name': 'Linked to Disk File',
    'file.active-file-info.description': 'This page can write to a local file on your computer. Saving will directly update that file — no need to re-download.',

    'clipboard.cut.name': 'Cut',
    'clipboard.copy.name': 'Copy',
    'clipboard.paste.name': 'Paste',
    'clipboard.paste-in-selection.name': 'Paste In Selection',

    'selection.select-all.name': 'Select All',

    'state.undo.name': 'Undo',
    'state.redo.name': 'Redo',
    
    'view.grid-settings.name': 'Grid Settings',
    'view.show-grid.name': 'Show Grid',
    'view.hide-grid.name': 'Hide Grid',
    'view.show-whitespace.name': 'Show Whitespace',
    'view.hide-whitespace.name': 'Hide Whitespace',
    'view.zoom-in.name': 'Zoom In',
    'view.zoom-out.name': 'Zoom Out',
    'view.zoom-fit.name': 'Zoom Fit',

    'settings.open-project-settings-dialog.name': 'Project Settings',
    'settings.open-font-dialog.name': 'Font Settings',
    'settings.open-resize-dialog.name': 'Resize Canvas',
    'settings.open-background-dialog.name': 'Color / Background Settings',

    'settings.change-background.invert-white.warning': "Your canvas contains white text, which won't be visible against a white background.",
    'settings.change-background.invert-white.checkbox': "Convert all white text to black",
    'settings.change-background.invert-black.warning': "Your canvas contains black text, which won't be visible against a black background.",
    'settings.change-background.invert-black.checkbox': "Convert all black text to white",

    'themes.select-os.name': 'System Default',
    'themes.select-light-mode.name': 'Light',
    'themes.select-dark-mode.name': 'Dark',

    'tools.standard.text-editor.name': 'Text Editor',
    'tools.standard.text-editor.description': 'Use this tool to edit text directly on the canvas.\n\n' +
        'Click to place the cursor and start typing. Click and drag to select text for copying, moving, or applying transformations.',
    'tools.standard.eraser.name': 'Eraser',
    'tools.standard.eraser.description': 'Click and drag to remove characters.',
    'tools.standard.fill-char.name': 'Fill Character',
    // 'tools.standard.fill-char.description': 'Fill a connected area of matching characters with the selected character.',
    // 'tools.standard.fill-char.diagonal': 'Include diagonally connected cells',
    // 'tools.standard.fill-char.colorblind': 'Include connected cells regardless of color',
    'tools.standard.fill-char.description': 'Fill an area with the selected character.',
    'tools.standard.fill-char.diagonal': 'Fills across diagonal connections',
    'tools.standard.fill-char.colorblind': 'Fills connected cells regardless of color',
    'tools.standard.draw-freeform.name': 'Draw Freeform Line',
    'tools.standard.draw-freeform.description': 'Draws a freeform line. Can either use the selected character or an auto-generated ASCII sequence.',
    'tools.standard.draw-rect.name': 'Draw Rectangle',
    'tools.standard.draw-rect.description': 'Draws a rectangle out of ASCII characters.',
    'tools.standard.draw-line.name': 'Draw Line',
    'tools.standard.draw-line.description': 'Draws a line out of ASCII characters.',
    'tools.standard.draw-ellipse.name': 'Draw Ellipse',
    'tools.standard.draw-ellipse.description': 'Draws an ellipse out of ASCII characters.',
    'tools.standard.selection.multiple': 'Create multiple selections',
    'tools.standard.selection-rect.name': 'Rectangle Selection',
    'tools.standard.selection-rect.description': 'Select a rectangular area to move, copy, or modify. ' +
        'After a selection has been made, press any key to fill the selection with that character.',
    'tools.standard.selection-rect.outline': 'Only select rectangle outline',
    'tools.standard.selection-line.name': 'Line Selection',
    'tools.standard.selection-line.description': 'Select a linear area to move, copy, or modify. ' +
        'After a selection has been made, press any key to fill the selection with that character.',
    'tools.standard.selection-lasso.name': 'Lasso Selection',
    'tools.standard.selection-lasso.description': 'Select an irregular area to move, copy, or modify. ' +
        'After a selection has been made, press any key to fill the selection with that character.',
    'tools.standard.selection-wand.name': 'Shape Selection',
    'tools.standard.selection-wand.description': 'Select a connected area of matching colors. ',
    'tools.standard.selection-wand.diagonal': 'Include diagonally connected cells',
    'tools.standard.selection-wand.colorblind': 'Include connected cells regardless of color',
    'tools.standard.pan.name': 'Hand (Panning Tool)',
    'tools.standard.pan.description': 'Click and drag to pan the view.',
    'tools.standard.move-all.name': 'Move All Content',
    'tools.standard.move-all.description': 'Click and drag to move all canvas content.',
    'tools.standard.move-all.all-layers': 'Apply to all layers',
    'tools.standard.move-all.all-frames': 'Apply to all frames',
    'tools.standard.move-all.wrap': 'Wrap canvas borders',
    'tools.standard.paint-brush.name': 'Paint Brush',
    'tools.standard.paint-brush.description': 'Click and drag to color cells with the selected color.',
    'tools.standard.fill-color.name': 'Fill Color',
    'tools.standard.fill-color.description': 'Fill a connected area of matching colors with the selected color.',
    'tools.standard.fill-color.diagonal': 'Include diagonally connected cells',
    'tools.standard.fill-color.colorblind': 'Include connected cells regardless of color',
    'tools.standard.color-swap.name': 'Color Swap',
    'tools.standard.color-swap.description': 'Click on a cell to replace all instances of that cell\'s color with the selected color.',
    'tools.standard.color-swap.all-layers': 'Apply to all layers',
    'tools.standard.color-swap.all-frames': 'Apply to all frames',
    'tools.standard.eyedropper.name': 'Eyedropper',
    'tools.standard.eyedropper.description': 'Click on a cell to put its color in the color picker.',
    'tools.standard.eyedropper.add-to-palette': 'Also add the color to the current palette.',

    'tools.standard.char-picker.name': 'Selected Character',
    'tools.standard.char-picker.description': 'Click to open the character picker. While open, pressing a key will select that character.',
    'tools.standard.quick-swap-char.name': 'Quick-Swap Mode',
    'tools.standard.quick-swap-char.description': 'While active, pressing any key selects that character instead of switching tools.\n\n' +
        "If a raster selection is active, Quick-Swap Mode is automatically enabled&mdash;pressing a key will fill the selection with the chosen character.",

    'tools.standard.color-picker.name': 'Selected Color',
    'tools.standard.color-picker.description': 'Click to open the color picker.',
    'tools.standard.color-picker-add.name': 'Add Color To Palette',
    'tools.standard.color-picker-add.description': 'This color is not currently saved to your palette. Click here if you want to add it.',

    'tools.selection.move.name': 'Move Selected Content',
    'tools.selection.move.description': 'When activated, clicking and dragging on the selected area will move the content.',
    'tools.selection.flip-v.name': 'Flip Vertically',
    'tools.selection.flip-v.description': 'Mirrors the selected content vertically.',
    'tools.selection.flip-v.mirror': 'Mirrors characters when possible, e.g. b => p',
    'tools.selection.flip-h.name': 'Flip Horizontally',
    'tools.selection.flip-h.description': 'Mirrors the selected content horizontally.',
    'tools.selection.flip-h.mirror': 'Mirrors characters when possible, e.g. b => d',
    'tools.selection.clone.name': 'Clone Selection',
    'tools.selection.clone.description': 'Clones the current selection to all frames.',
    'tools.selection.fill-char.name': 'Fill Selection With Character',
    'tools.selection.fill-char.description': 'Fills the selected area with the selected character. \n\n' +
        'Alternatively, press any key on your keyboard to fill the selection with that character.',
    'tools.selection.fill-color.name': 'Fill Selection With Color',
    'tools.selection.fill-color.description': 'Paints the selected area with the selected color.',
    'tools.selection.convert-to-whitespace.name': 'Fill Blank Cells with Whitespace',
    'tools.selection.convert-to-whitespace.description': 'Replaces all blank cells with whitespace cells. ' +
        'Whitespace blocks lower layers when multiple layers are visible.',
    'tools.selection.convert-to-empty.name': 'Remove Whitespace',
    'tools.selection.convert-to-empty.description': 'Replaces all whitespace cells with blank cells. ' +
        'Blank cells allow lower layers to show through.',
    'tools.selection.resize.name': 'Resize Canvas',
    'tools.selection.resize.description': 'Resizes the canvas to match the selected area.',
    'tools.selection.close.name': 'Close',
    'tools.selection.close.description': 'Closes the current selection.',

    'tools.brush.square-1.name': 'Square Brush',
    'tools.brush.square-1.description': 'Size: 1',
    'tools.brush.square-2.name': 'Square Brush',
    'tools.brush.square-2.description': 'Size: 2',
    'tools.brush.square-3.name': 'Square Brush',
    'tools.brush.square-3.description': 'Size: 3',
    'tools.brush.square-5.name': 'Square Brush',
    'tools.brush.square-5.description': 'Size: 5',
    'tools.brush.square-10.name': 'Square Brush',
    'tools.brush.square-10.description': 'Size: 10',
    'tools.brush.circle-3.name': 'Circle Brush',
    'tools.brush.circle-3.description': 'Size: 3',
    'tools.brush.circle-5.name': 'Circle Brush',
    'tools.brush.circle-5.description': 'Size: 5',
    'tools.brush.circle-10.name': 'Circle Brush',
    'tools.brush.circle-10.description': 'Size: 10',

    'tools.shapes.freeformStroke.name': 'Freeform Style',
    'tools.shapes.freeformStroke.irregular-monochar.name': 'Single-Character Line',
    'tools.shapes.freeformStroke.irregular-monochar.description': 'Draws a line by repeating the selected character.',
    'tools.shapes.freeformStroke.irregular-adaptive.name': 'Autogenerated ASCII Line',
    'tools.shapes.freeformStroke.irregular-adaptive.description': 'Draws a smooth ASCII line. Characters are picked automatically based on how the line crosses each cell.',

    'tools.shapes.rectStroke.name': 'Rectangle Style',
    'tools.shapes.rectStroke.outline-ascii-1.name': 'Characters: /---\\',
    'tools.shapes.rectStroke.outline-ascii-1.description': 'Uses only basic ASCII characters.',
    'tools.shapes.rectStroke.outline-ascii-2.name': 'Characters: +---+',
    'tools.shapes.rectStroke.outline-ascii-2.description': 'Uses only basic ASCII characters.',
    'tools.shapes.rectStroke.outline-unicode-1.name': 'Characters: ┌───┐',
    'tools.shapes.rectStroke.outline-unicode-1.description': 'Uses Unicode characters.',
    'tools.shapes.rectStroke.outline-unicode-2.name': 'Characters: ╔═══╗',
    'tools.shapes.rectStroke.outline-unicode-2.description': 'Uses Unicode characters.',
    'tools.shapes.rectStroke.outline-monochar.name': 'Single-Character Outline',
    'tools.shapes.rectStroke.outline-monochar.description': 'Draws a rectangle outline by repeating the selected character.',

    'tools.shapes.lineStroke.name': 'Line Style',
    'tools.shapes.lineStroke.straight-adaptive.name': 'Autogenerated Straight ASCII Line',
    'tools.shapes.lineStroke.straight-adaptive.description': 'Draws a straight line using various ASCII characters to best fit the slope.',
    'tools.shapes.lineStroke.straight-monochar.name': 'Straight Single-Character Line',
    'tools.shapes.lineStroke.straight-monochar.description': 'Draws a straight line by repeating the selected character.',

    'tools.shapes.ellipseStroke.name': 'Ellipse Style',
    'tools.shapes.ellipseStroke.outline-monochar.name': 'Ellipse Outline',
    'tools.shapes.ellipseStroke.outline-monochar.description': 'Draws an ellipse outline by repeating the selected character.',

    'tools.shapes.fill.name': 'Fill Style',
    'tools.shapes.fill.description': "Controls how the shape's background is rendered.",
    'tools.shapes.fill.empty.name': 'Empty',
    'tools.shapes.fill.empty.description': 'No background fill; shapes behind will remain visible.',
    'tools.shapes.fill.whitespace.name': 'Whitespace',
    'tools.shapes.fill.whitespace.description': 'Fills the background with whitespace. Background appears empty but blocks shapes underneath.',
    'tools.shapes.fill.monochar.name': 'Solid Char',
    'tools.shapes.fill.monochar.description': "Fills the background with the shape's selected character",

    'tools.shapes.char-picker.name': 'Shape Character',
    'tools.shapes.char-picker.description': 'Character used for certain stroke/fill styles. While open, pressing a key will select that character.',
    'tools.shapes.color-picker.name': 'Shape Color',
    'tools.shapes.color-picker.description': 'Click to open the color picker.',

    'tools.shapes.order.name': 'Order',
    'tools.shapes.sendToBack.name': 'Send To Back',
    'tools.shapes.sendBackward.name': 'Send Backward',
    'tools.shapes.bringForward.name': 'Bring Forward',
    'tools.shapes.bringToFront.name': 'Bring To Front',
    'tools.shapes.delete.name': 'Delete Shape',

    'tools.shapes.startCursor.name': 'Start Cursor',

    'tools.shapes.textAlignH.name': 'Horizontal Alignment',
    'tools.shapes.textAlignH.alignLeft.name': 'Align Left',
    'tools.shapes.textAlignH.alignCenter.name': 'Align Center',
    'tools.shapes.textAlignH.alignRight.name': 'Align Right',

    'tools.shapes.textAlignV.name': 'Vertical Alignment',
    'tools.shapes.textAlignV.alignTop.name': 'Align Top',
    'tools.shapes.textAlignV.alignMiddle.name': 'Align Middle',
    'tools.shapes.textAlignV.alignBottom.name': 'Align Bottom',

    'frames.new-frame.name': 'New Frame',
    'frames.new-frame.description': 'Creates a new blank frame.',
    'frames.duplicate-frame.name': 'Duplicate Frame',
    'frames.duplicate-frame.description': 'Duplicates the currently selected frame(s).',
    'frames.delete-frame.name': 'Delete Frame',
    'frames.delete-frame.description': 'Deletes the currently selected frame(s).',
    'frames.reverse-frames.name': 'Reverse Frames',
    'frames.reverse-frames.description': 'Reverses the order of the currently selected frames.',
    'frames.toggle-onion.name': 'Toggle Onion',
    'frames.toggle-onion.description': 'When enabled, the previous frame will be faintly displayed.',
    'frames.toggle-ticks.name': 'Show Frame Ticks',
    'frames.toggle-ticks.description': 'Displays tick controls to customize how long each frame appears.\n\n' +
        'Tick counts are shown in the bottom-right corner of each frame and can be edited by clicking them. ' +
        'When multiple frames are selected, the change is applied to all.',
    'frames.show-component.name': 'Maximize Frames View',
    'frames.show-component.description': 'Shows the frames component.',
    'frames.hide-component.name': 'Minimize Frames View',
    'frames.hide-component.description': 'Hides the frames component.',
    'frames.align-left.name': 'Align Frames: Left',
    'frames.align-left.description': 'Positions the frames on the left side of the screen.',
    'frames.align-bottom.name': 'Align Frames: Bottom',
    'frames.align-bottom.description': 'Positions the frames on the bottom of the screen.',
    'frames.previous-frame.name': 'Previous Frame',
    'frames.next-frame.name': 'Next Frame',

    'layers.add-layer.name': 'Add Layer',
    'layers.add-layer.description': 'Creates a new layer.',
    'layers.edit-layer.name': 'Edit Layer',
    'layers.edit-layer.description': 'Edit the current layer\'s name. Layers can also be reordered by clicking and dragging them.',
    'layers.delete-layer.name': 'Delete Layer',
    'layers.delete-layer.description': 'Deletes the current layer.',
    'layers.toggle-visibility-lock.name': 'Toggle Layer Visibility',
    'layers.toggle-visibility-lock.description': 'When locked, only the current layer is shown in the main canvas. ' +
        'When unlocked, you can manually show/hide all layers.',
    'layers.layerType.vector.name': 'Vector Layer',
    'layers.layerType.vector.description': "In vector layers, shapes are preserved as editable objects, allowing you to continually modify or resize them. " +
        'Vector layers are ideal for diagrams, flowcharts, schematics, and other structured layouts.',
    'layers.layerType.vectorize.warning': 'Raster layers cannot be converted to vector layers.',
    'layers.layerType.raster.name': 'Raster Layer',
    'layers.layerType.raster.description': 'In raster layers, each grid cell is independent and holds its own character. ' +
        'You can freely erase, overwrite, or repaint any part of the canvas. Raster layers are ideal for detailed editing and creating ASCII art.',
    'layers.layerType.rasterize.warning': 'This layer will be rasterized: it will appear the same, but all shapes will be converted to raw characters.',

    'preview.open-popup.name': 'Preview Popup',
    'preview.open-popup.description': 'Opens the preview in a resizeable popup window.',
    'preview.play.name': 'Play Preview',
    'preview.play.description': 'Plays the preview at the given FPS.',
    'preview.pause.name': 'Pause Preview',
    'preview.pause.description': 'Pauses the preview on the current frame.',

    'palette.sort-colors.name.date-added': 'Sorting By: Date Added',
    'palette.sort-colors.name.hue': 'Sorting By: Hue',
    'palette.sort-colors.name.saturation': 'Sorting By: Saturation',
    'palette.sort-colors.name.lightness': 'Sorting By: Lightness',
    'palette.sort-colors.name.alpha': 'Sorting By: Alpha',
    'palette.sort-colors.description': 'Click to change sorting method.',
    'palette.delete-color.name': 'Delete Color',
    'palette.delete-color.description': 'Removes the selected color from your palette. This does not affect characters already using the color.',
    'palette.open-settings.name': 'Palette Settings',
    'palette.open-settings.description': 'TODO',
    'palette.empty': 'No colors added.',

    'unicode.information.name': 'Unicode Quick Reference',
    'unicode.information.description': "Unicode characters aren't part of standard ASCII, but they're sometimes used in " +
        "ASCII art for their unique shapes and styles. Any time you use a Unicode character in your drawing it'll automatically " +
        'appear here for easy access and reuse.\n\n' +
        'Click a character below to select it in the character picker. ' +
        "This may also have additional effects depending on the tool you're using:\n" +
        '• Text Editor: Pastes the character once\n' +
        '• Selections: Fill selected area with the character',
    'unicode.open-settings.name': 'Unicode Settings',
    'unicode.open-settings.description': 'Opens unicode character settings.',
    'unicode.empty': 'No characters added.',

    'warnings.current-layer-not-visible': 'The current layer is not visible!',

    'sidebar.show-component.name': 'Maximize Sidebar',
    'sidebar.show-component.description': 'Shows the sidebar content.',
    'sidebar.hide-component.name': 'Minimize Sidebar',
    'sidebar.hide-component.description': 'Hides the sidebar content.',

}
