
export const strings = {
    'file.new-file.name': 'New File',
    'file.open-file.name': 'Open File',
    'file.save-file.name': 'Save File',
    'file.export-file.name': 'Export To...',
    'file.resize-canvas.name': 'Resize Canvas',
    'file.background-settings.name': 'Background Settings',

    'clipboard.cut.name': 'Cut',
    'clipboard.copy.name': 'Copy',
    'clipboard.paste.name': 'Paste',
    'clipboard.paste-in-selection.name': 'Paste In Selection',

    'selection.select-all.name': 'Select All',

    'state.undo.name': 'Undo',
    'state.redo.name': 'Redo',

    'editor.tools.text-editor.name': 'Text Editor Tool',
    'editor.tools.text-editor.description': 'Click to place your cursor, then type to enter text characters. Click and drag to highlight text.',
    'editor.tools.eraser.name': 'Eraser Tool',
    'editor.tools.eraser.description': 'Click and drag to remove characters.',
    'editor.tools.draw-freeform.name': 'Draw Character Tool',
    'editor.tools.draw-freeform.description': 'Click and drag to continuously draw the chosen character. Type a key to change the character.',
    'editor.tools.selection.multiple': 'Create multiple selections',
    'editor.tools.selection-rect.name': 'Rectangle Selection',
    'editor.tools.selection-rect.description': 'Click and drag to select a rectangular area. Once an area is selected, typing a key will fill the selection with that character.',
    'editor.tools.selection-line.name': 'Line Selection',
    'editor.tools.selection-line.description': 'Click and drag to select a linear area. Once an area is selected, typing a key will fill the selection with that character.',
    'editor.tools.selection-lasso.name': 'Lasso Selection',
    'editor.tools.selection-lasso.description': 'Click and drag to select a irregular area. Once an area is selected, typing a key will fill the selection with that character.',
    'editor.tools.selection-wand.name': 'Shape Selection',
    'editor.tools.selection-wand.description': 'Click on a cell to select it and all connected cells of the same color. Once an area is selected, typing a key will fill the selection with that character.',
    'editor.tools.selection-wand.diagonal': 'Include diagonal connections',
    'editor.tools.selection-wand.colorblind': 'Include connected cells regardless of color',
    'editor.tools.paint-brush.name': 'Paint Brush Tool',
    'editor.tools.paint-brush.description': 'Click and drag to apply a color to an area.',
    'editor.tools.paint-bucket.name': 'Paint Bucket Tool',
    'editor.tools.paint-bucket.description': 'Click on a cell to apply a color to the cell and all connected cells of the same color.',
    'editor.tools.eyedropper.name': 'Eyedropper Tool',
    'editor.tools.eyedropper.description': 'Click on a cell to put its color in the color picker.',
    'editor.tools.eyedropper.add-to-palette': 'Add the color to the current palette.',

    'editor.selection.move.name': 'Move Selected Content',
    'editor.selection.move.description': 'When activated, clicking and dragging on the selected area will move the content.',
    'editor.selection.typewriter.name': 'Type Within Selection',
    'editor.selection.typewriter.description': 'When activated, content can be typed into the selection one character at a time. The cursor can be moved with the arrow keys, and will wrap when it reaches the end of the selection.',
    'editor.selection.flip-v.name': 'Flip Vertically',
    'editor.selection.flip-v.description': 'Mirrors the selected content vertically.',
    'editor.selection.flip-v.mirror': 'Mirrors characters when possible, e.g. b => p',
    'editor.selection.flip-h.name': 'Flip Horizontally',
    'editor.selection.flip-h.description': 'Mirrors the selected content horizontally.',
    'editor.selection.flip-h.mirror': 'Mirrors characters when possible, e.g. b => d',
    'editor.selection.clone.name': 'Clone Selection',
    'editor.selection.clone.description': 'Clones the current selection to all frames.',
    'editor.selection.paint-bucket.name': 'Paint Selection',
    'editor.selection.paint-bucket.description': 'Paints the selected area with the current color.',
    'editor.selection.resize.name': 'Resize Canvas',
    'editor.selection.resize.description': 'Resizes the canvas to match the selected area.',
    'editor.selection.close.name': 'Close',
    'editor.selection.close.description': 'Closes the current selection.',

    'timeline.add-frame.name': 'Add Frame',
    'timeline.add-frame.description': 'Creates a blank frame.',
    'timeline.duplicate-frame.name': 'Duplicate Frame',
    'timeline.duplicate-frame.description': 'Makes a copy of the current frame.',
    'timeline.delete-frame.name': 'Delete Frame',
    'timeline.delete-frame.description': 'Deletes the current frame.',
    'timeline.toggle-onion.name': 'Toggle Onion',
    'timeline.toggle-onion.description': 'When enabled, the previous frame will be faintly displayed.',
    'timeline.align-frames-left.name': 'Align Frames: Left',
    'timeline.align-frames-left.description': 'Positions the frames on the left side of the screen.',
    'timeline.align-frames-bottom.name': 'Align Frames: Bottom',
    'timeline.align-frames-bottom.description': 'Positions the frames on the bottom of the screen.',

    'timeline.add-layer.name': 'Add Layer',
    'timeline.add-layer.description': 'Creates a new layer.',
    'timeline.edit-layer.name': 'Edit Layer',
    'timeline.edit-layer.description': 'Edit the current layer\'s name. Layers can also be reordered by clicking and dragging them.',
    'timeline.delete-layer.name': 'Delete Layer',
    'timeline.delete-layer.description': 'Deletes the current layer.',
    'timeline.toggle-layer-visibility-lock.name': 'Toggle Layer Visibility',
    'timeline.toggle-layer-visibility-lock.description': 'When locked, only the current layer is shown in the main canvas. When unlocked, you can manually show/hide all layers.',

    'zoom.zoom-in.name': 'Zoom In',
    'zoom.zoom-out.name': 'Zoom Out',
    'zoom.zoom-fit.name': 'Zoom Fit',
    'view.grid-settings.name': 'Grid Settings',
    'view.show-grid.name': 'Show Grid',
    'view.hide-grid.name': 'Hide Grid',
}
