
export const strings = {
    'editingTools.text-editor.title': 'Text Editor Tool',
    'editingTools.text-editor.description': 'Click to place your cursor, then type to enter text characters. Click and drag to highlight text.',
    'editingTools.draw-freeform.title': 'Draw Character Tool',
    'editingTools.draw-freeform.description': 'Click and drag to continuously draw the chosen character. Type a key to change the character.',
    'editingTools.selection.multiple': 'Create multiple selections',
    'editingTools.selection-rect.title': 'Rectangle Selection',
    'editingTools.selection-rect.description': 'Click and drag to select a rectangular area. Once an area is selected, typing a key will fill the selection with that character.',
    'editingTools.selection-line.title': 'Line Selection',
    'editingTools.selection-line.description': 'Click and drag to select a linear area. Once an area is selected, typing a key will fill the selection with that character.',
    'editingTools.selection-lasso.title': 'Lasso Selection',
    'editingTools.selection-lasso.description': 'Click and drag to select a irregular area. Once an area is selected, typing a key will fill the selection with that character.',
    'editingTools.selection-wand.title': 'Shape Selection',
    'editingTools.selection-wand.description': 'Click on a cell to select it and all connected cells of the same color. Once an area is selected, typing a key will fill the selection with that character.',
    'editingTools.selection-wand.diagonal': 'Include diagonal connections',
    'editingTools.selection-wand.colorblind': 'Find connected cells of any color',
    'editingTools.paint-brush.title': 'Paint Brush Tool',
    'editingTools.paint-brush.description': 'Click and drag to apply a color to an area.',
    'editingTools.paint-bucket.title': 'Paint Bucket Tool',
    'editingTools.paint-bucket.description': 'Click on a cell to apply a color to the cell and all connected cells of the same color.',
    'editingTools.eyedropper.title': 'Eyedropper Tool',
    'editingTools.eyedropper.description': 'Click on a cell to put its color in the color picker.',

    'selectionTools.move.title': 'Move Selection',
    'selectionTools.move.description': 'When activated, clicking and dragging on the selected area will move the content.',
    'selectionTools.typewriter.title': 'Type Within Selection',
    'selectionTools.typewriter.description': 'When activated, content can be typed into the selection one character at a time. The cursor can be moved with the arrow keys, and will wrap when it reaches the end of the selection.',
    'selectionTools.flip-v.title': 'Flip Vertically',
    'selectionTools.flip-v.description': 'Mirrors the selected content vertically.',
    'selectionTools.flip-v.mirror': 'Mirrors characters when possible, e.g. b => p',
    'selectionTools.flip-h.title': 'Flip Horizontally',
    'selectionTools.flip-h.description': 'Mirrors the selected content horizontally.',
    'selectionTools.flip-h.mirror': 'Mirrors characters when possible, e.g. b => d',
    'selectionTools.paint-bucket.title': 'Paint Selection',
    'selectionTools.paint-bucket.description': 'Paints the selected area with the current color.',
    'selectionTools.resize.title': 'Resize Canvas',
    'selectionTools.resize.description': 'Resizes the canvas to match the selected area.',
    'selectionTools.close.title': 'Close',
    'selectionTools.close.description': 'Closes the current selection.',
}
